export const PAGINATION = {
  DEFAULT_PAGE: 0,
  DEFAULT_PAGE_SIZE: Number(import.meta.env.VITE_DEFAULT_PAGE_SIZE) || 10,
  MAX_PAGE_SIZE: Number(import.meta.env.VITE_MAX_PAGE_SIZE) || 100,
  SEARCH_DEBOUNCE_DELAY: Number(import.meta.env.VITE_SEARCH_DEBOUNCE_DELAY) || 300,
  DOCTOR_SEARCH_SIZE:Number(import.meta.env.VITE_DOCTOR_SEARCH_SIZE) || 5,
  DOCTOR_SEARCH_MIN_LENGTH:Number(import.meta.env.VITE_DOCTOR_SEARCH_MIN_LENGTH) || 2,
  MEDICAL_SERVICE_SEARCH_SIZE:Number(import.meta.env.VITE_MEDICAL_SERVICE_SEARCH_SIZE) || 5,
  LABORATORY_PAGE_SIZE:Number(import.meta.env.VITE_LABORATORY_PAGE_SIZE) || 10,
  MEDICINE_PAGE_SIZE:Number(import.meta.env.VITE_MEDICINE_PAGE_SIZE) || 10,
  MEDICINE_CATEGORY_PAGE_SIZE:Number(import.meta.env.VITE_MEDICINE_CATEGORY_PAGE_SIZE) || 10 ,
  MEDICINE_CATEGORY_SEARCH_SIZE : Number(import.meta.env.VITE_MEDICINE_CATEGORY_SEARCH_SIZE) || 5,
  MEDICINE_CATEGORY_SEARCH_MIN_LENGTH : Number(import.meta.env.VITE_MEDICINE_CATEGORY_SEARCH_MIN_LENGTH) || 2,
  MEDICINE_SEARCH_SIZE:Number(import.meta.env.VITE_MEDICINE_SEARCH_SIZE) || 5,
  MEDICINE_SEARCH_MIN_LENGTH:Number(import.meta.env.VITE_MEDICINE_SEARCH_MIN_LENGTH) || 2,
  PRESCRIPTION_PAGE_SIZE:Number(import.meta.env.VITE_PRESCRIPTION_PAGE_SIZE) || 10,
  INVOICE_PAGE_SIZE:Number(import.meta.env.VITE_INVOICE_PAGE_SIZE) || 10,

};
  
  